package net.sourceforge.lept4j;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.ptr.PointerByReference;
import java.util.Arrays;
import java.util.List;
/**
 * Array of Boxa<br>
 * <i>native declaration : pix.h:116</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class Boxaa extends Structure {
	/**
	 * number of boxa in ptr array<br>
	 * C type : l_int32
	 */
	public int n;
	/**
	 * number of boxa ptrs allocated<br>
	 * C type : l_int32
	 */
	public int nalloc;
	/**
	 * boxa ptr array<br>
	 * C type : Boxa**
	 */
	public PointerByReference boxa;
	public Boxaa() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("n", "nalloc", "boxa");
	}
	/**
	 * @param n number of boxa in ptr array<br>
	 * C type : l_int32<br>
	 * @param nalloc number of boxa ptrs allocated<br>
	 * C type : l_int32<br>
	 * @param boxa boxa ptr array<br>
	 * C type : Boxa**
	 */
	public Boxaa(int n, int nalloc, PointerByReference boxa) {
		super();
		this.n = n;
		this.nalloc = nalloc;
//		if ((boxa.length != this.boxa.length)) 
//			throw new IllegalArgumentException("Wrong array size !");
		this.boxa = boxa;
	}
	public Boxaa(Pointer peer) {
		super(peer);
		read();
	}
	public static class ByReference extends Boxaa implements Structure.ByReference {
		
	};
	public static class ByValue extends Boxaa implements Structure.ByValue {
		
	};
}
