package net.sourceforge.lept4j;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : jbclass.h:29</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class JbClasser extends Structure {
	/**
	 * input page image file names<br>
	 * C type : Sarray*
	 */
	public net.sourceforge.lept4j.Sarray.ByReference safiles;
	/**
	 * JB_RANKHAUS, JB_CORRELATION<br>
	 * C type : l_int32
	 */
	public int method;
	/**
	 * JB_CONN_COMPS, JB_CHARACTERS or<br>
	 * C type : l_int32
	 */
	public int components;
	/**
	 * max component width allowed<br>
	 * C type : l_int32
	 */
	public int maxwidth;
	/**
	 * max component height allowed<br>
	 * C type : l_int32
	 */
	public int maxheight;
	/**
	 * number of pages already processed<br>
	 * C type : l_int32
	 */
	public int npages;
	/**
	 * number of components already processed<br>
	 * C type : l_int32
	 */
	public int baseindex;
	/**
	 * number of components on each page<br>
	 * C type : Numa*
	 */
	public net.sourceforge.lept4j.Numa.ByReference nacomps;
	/**
	 * size of square struct element for haus<br>
	 * C type : l_int32
	 */
	public int sizehaus;
	/**
	 * rank val of haus match, each way<br>
	 * C type : l_float32
	 */
	public float rankhaus;
	/**
	 * thresh value for correlation score<br>
	 * C type : l_float32
	 */
	public float thresh;
	/**
	 * corrects thresh value for heaver<br>
	 * C type : l_float32
	 */
	public float weightfactor;
	/**
	 * w * h of each template, without extra<br>
	 * C type : Numa*
	 */
	public net.sourceforge.lept4j.Numa.ByReference naarea;
	/**
	 * max width of original src images<br>
	 * C type : l_int32
	 */
	public int w;
	/**
	 * max height of original src images<br>
	 * C type : l_int32
	 */
	public int h;
	/**
	 * current number of classes<br>
	 * C type : l_int32
	 */
	public int nclass;
	/**
	 * If zero, pixaa isn't filled<br>
	 * C type : l_int32
	 */
	public int keep_pixaa;
	/**
	 * instances for each class; unbordered<br>
	 * C type : Pixaa*
	 */
	public net.sourceforge.lept4j.Pixaa.ByReference pixaa;
	/**
	 * templates for each class; bordered<br>
	 * C type : Pixa*
	 */
	public net.sourceforge.lept4j.Pixa.ByReference pixat;
	/**
	 * templates for each class; bordered<br>
	 * C type : Pixa*
	 */
	public net.sourceforge.lept4j.Pixa.ByReference pixatd;
	/**
	 * Hash table to find templates by size<br>
	 * C type : L_DnaHash*
	 */
	public net.sourceforge.lept4j.L_DnaHash.ByReference dahash;
	/**
	 * fg areas of undilated templates;<br>
	 * C type : Numa*
	 */
	public net.sourceforge.lept4j.Numa.ByReference nafgt;
	/**
	 * centroids of all bordered cc<br>
	 * C type : Pta*
	 */
	public net.sourceforge.lept4j.Pta.ByReference ptac;
	/**
	 * centroids of all bordered template cc<br>
	 * C type : Pta*
	 */
	public net.sourceforge.lept4j.Pta.ByReference ptact;
	/**
	 * array of class ids for each component<br>
	 * C type : Numa*
	 */
	public net.sourceforge.lept4j.Numa.ByReference naclass;
	/**
	 * array of page nums for each component<br>
	 * C type : Numa*
	 */
	public net.sourceforge.lept4j.Numa.ByReference napage;
	/**
	 * array of UL corners at which the<br>
	 * C type : Pta*
	 */
	public net.sourceforge.lept4j.Pta.ByReference ptaul;
	/**
	 * similar to ptaul, but for LL corners<br>
	 * C type : Pta*
	 */
	public net.sourceforge.lept4j.Pta.ByReference ptall;
	public JbClasser() {
		super();
	}
	/**
	 * Gets this Structure's field names in their proper order.
	 * @return list of ordered field names
	 */
	@Override
	protected List<String> getFieldOrder() {
		return Arrays.asList("safiles", "method", "components", "maxwidth", "maxheight", "npages", "baseindex", "nacomps", "sizehaus", "rankhaus", "thresh", "weightfactor", "naarea", "w", "h", "nclass", "keep_pixaa", "pixaa", "pixat", "pixatd", "dahash", "nafgt", "ptac", "ptact", "naclass", "napage", "ptaul", "ptall");
	}
	public JbClasser(Pointer peer) {
		super(peer);
		read();
	}
	public static class ByReference extends JbClasser implements Structure.ByReference {
		
	};
	public static class ByValue extends JbClasser implements Structure.ByValue {
		
	};
}
