package net.sourceforge.lept4j;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : rbtree.h:15</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class L_Rbtree extends Structure {
	/** C type : L_Rbtree_Node* */
	public net.sourceforge.lept4j.L_Rbtree_Node.ByReference root;
	/** C type : l_int32 */
	public int keytype;
	public L_Rbtree() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("root", "keytype");
	}
	/**
	 * @param root C type : L_Rbtree_Node*<br>
	 * @param keytype C type : l_int32
	 */
	public L_Rbtree(net.sourceforge.lept4j.L_Rbtree_Node.ByReference root, int keytype) {
		super();
		this.root = root;
		this.keytype = keytype;
	}
	public L_Rbtree(Pointer peer) {
		super(peer);
                read();
	}
	public static class ByReference extends L_Rbtree implements Structure.ByReference {
		
	};
	public static class ByValue extends L_Rbtree implements Structure.ByValue {
		
	};
}
