package net.sourceforge.lept4j;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.ptr.PointerByReference;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : array.h:20</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class Numa2d extends Structure {
	/**
	 * number of rows allocated for ptr array<br>
	 * C type : l_int32
	 */
	public int nrows;
	/**
	 * number of cols allocated for ptr array<br>
	 * C type : l_int32
	 */
	public int ncols;
	/**
	 * initial size of each numa that is made<br>
	 * C type : l_int32
	 */
	public int initsize;
	/**
	 * 2D array of Numa<br>
	 * C type : Numa***
	 */
	public PointerByReference numa;
	public Numa2d() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("nrows", "ncols", "initsize", "numa");
	}
	/**
	 * @param nrows number of rows allocated for ptr array<br>
	 * C type : l_int32<br>
	 * @param ncols number of cols allocated for ptr array<br>
	 * C type : l_int32<br>
	 * @param initsize initial size of each numa that is made<br>
	 * C type : l_int32<br>
	 * @param numa 2D array of Numa<br>
	 * C type : Numa***
	 */
	public Numa2d(int nrows, int ncols, int initsize, PointerByReference numa) {
		super();
		this.nrows = nrows;
		this.ncols = ncols;
		this.initsize = initsize;
		this.numa = numa;
	}
	public Numa2d(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends Numa2d implements Structure.ByReference {
		
	};
	public static class ByValue extends Numa2d implements Structure.ByValue {
		
	};
}
