package net.sourceforge.lept4j;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.ptr.PointerByReference;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : array.h:41</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class Sarray extends Structure {
	/**
	 * size of allocated ptr array<br>
	 * C type : l_int32
	 */
	public int nalloc;
	/**
	 * number of strings allocated<br>
	 * C type : l_int32
	 */
	public int n;
	/**
	 * reference count (1 if no clones)<br>
	 * C type : l_int32
	 */
	public int refcount;
	/**
	 * string array<br>
	 * C type : char**
	 */
	public PointerByReference array;
	public Sarray() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("nalloc", "n", "refcount", "array");
	}
	/**
	 * @param nalloc size of allocated ptr array<br>
	 * C type : l_int32<br>
	 * @param n number of strings allocated<br>
	 * C type : l_int32<br>
	 * @param refcount reference count (1 if no clones)<br>
	 * C type : l_int32<br>
	 * @param array string array<br>
	 * C type : char**
	 */
	public Sarray(int nalloc, int n, int refcount, PointerByReference array) {
		super();
		this.nalloc = nalloc;
		this.n = n;
		this.refcount = refcount;
		this.array = array;
	}
	public Sarray(Pointer peer) {
		super(peer);
		read();
	}
	public static class ByReference extends Sarray implements Structure.ByReference {
		
	};
	public static class ByValue extends Sarray implements Structure.ByValue {
		
	};
}
